name: Raise and nuture Kevin Malone

on:
  pull_request:
    branches:
      - "master"

env:
  APP_NAME: ${{ 'kevin-malone-test' }}

jobs:
  # Run code tests before building the image, to ensure it is good to go
  build:
    name: Run code tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t local .
      - name: Run tests
        run: docker run -it -v $PWD:/app -w/app local pytest .
      - name: Check format with black
        run: docker run -it -v $PWD:/app -w/app local black . --check
      - name: Lint with flake8
        run: docker run -it -v $PWD:/app -w/app local flake8 .
